import {
  ForecastDay,
  ForecastResponse,
  HourData,
  LocationResponse,
  SpecificDayResponse,
  WeatherResponse,
} from '@/types/weather';

export const mockSearchLocationData: LocationResponse[] = [
  {
    id: 3125553,
    name: 'Tokyo',
    region: 'Tokyo',
    country: 'Japan',
    lat: 35.69,
    lon: 139.69,
    url: 'tokyo-tokyo-japan',
  },
  {
    id: 317748,
    name: 'Toronto',
    region: 'Ontario',
    country: 'Canada',
    lat: 43.67,
    lon: -79.42,
    url: 'toronto-ontario-canada',
  },
  {
    id: 2206621,
    name: 'Tolyatti',
    region: 'Samara',
    country: 'Russia',
    lat: 53.52,
    lon: 49.41,
    url: 'tolyatti-samara-russia',
  },
  {
    id: 2314683,
    name: 'Touba',
    region: 'Diourbel',
    country: 'Senegal',
    lat: 15.86,
    lon: -16.39,
    url: 'touba-diourbel-senegal',
  },
  {
    id: 3200683,
    name: 'Toluca',
    region: 'México',
    country: 'Mexico',
    lat: 19.29,
    lon: -99.65,
    url: 'toluca-mxico-mexico',
  },
];

export const mockSuggestions = ['Tokyo', 'Toronto', 'Tolyatti', 'Touba', 'Toluca'];

export const mockCurrentWeather: WeatherResponse = {
  location: {
    name: 'Tokyo',
    region: 'Tokyo',
    country: 'Japan',
    lat: 35.69,
    lon: 139.69,
    tz_id: 'Asia/Tokyo',
    localtime_epoch: 1726244730,
    localtime: '2024-09-14 01:25',
  },
  current: {
    last_updated_epoch: 1726244100,
    last_updated: '2024-09-14 01:15',
    temp_c: 28.1,
    temp_f: 82.6,
    is_day: 0,
    condition: {
      text: '所により曇り',
      icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
      code: 1003,
    },
    wind_mph: 10.1,
    wind_kph: 16.2,
    wind_degree: 225,
    wind_dir: 'SW',
    pressure_mb: 1008.0,
    pressure_in: 29.77,
    precip_mm: 0.18,
    precip_in: 0.01,
    humidity: 70,
    cloud: 25,
    feelslike_c: 31.0,
    feelslike_f: 87.8,
    windchill_c: 28.7,
    windchill_f: 83.6,
    heatindex_c: 32.1,
    heatindex_f: 89.7,
    dewpoint_c: 22.5,
    dewpoint_f: 72.6,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 13.4,
    gust_kph: 21.5,
  },
};

export const mockForecastDay: ForecastDay = {
  date: '2024-09-14',
  date_epoch: 1726272000,
  day: {
    maxtemp_c: 32.5,
    maxtemp_f: 90.6,
    mintemp_c: 27.8,
    mintemp_f: 82.0,
    avgtemp_c: 29.8,
    avgtemp_f: 85.6,
    maxwind_mph: 20.6,
    maxwind_kph: 33.1,
    totalprecip_mm: 0.1,
    totalprecip_in: 0.0,
    totalsnow_cm: 0.0,
    avgvis_km: 10.0,
    avgvis_miles: 6.0,
    avghumidity: 66,
    daily_will_it_rain: 0,
    daily_chance_of_rain: 0,
    daily_will_it_snow: 0,
    daily_chance_of_snow: 0,
    condition: {
      text: '所により曇り',
      icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
      code: 1003,
    },
    uv: 8.0,
  },
  astro: {
    sunrise: '05:23 AM',
    sunset: '05:50 PM',
    moonrise: '03:36 PM',
    moonset: '12:14 AM',
    moon_phase: 'Waxing Gibbous',
    moon_illumination: 78,
    is_moon_up: 0,
    is_sun_up: 1,
  },
  hour: [
    {
      time_epoch: 1726239600,
      time: '2024-09-14 00:00',
      temp_c: 28.7,
      temp_f: 83.6,
      is_day: 0,
      condition: {
        text: '快晴',
        icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
        code: 1000,
      },
      wind_mph: 13.4,
      wind_kph: 21.6,
      wind_degree: 210,
      wind_dir: 'SSW',
      pressure_mb: 1008.0,
      pressure_in: 29.77,
      precip_mm: 0.0,
      precip_in: 0.0,
      snow_cm: 0.0,
      humidity: 68,
      cloud: 13,
      feelslike_c: 31.9,
      feelslike_f: 89.5,
      windchill_c: 28.7,
      windchill_f: 83.6,
      heatindex_c: 31.9,
      heatindex_f: 89.5,
      dewpoint_c: 22.3,
      dewpoint_f: 72.1,
      will_it_rain: 0,
      chance_of_rain: 0,
      will_it_snow: 0,
      chance_of_snow: 0,
      vis_km: 10.0,
      vis_miles: 6.0,
      gust_mph: 17.8,
      gust_kph: 28.6,
      uv: 0,
    },
    {
      time_epoch: 1726243200,
      time: '2024-09-14 01:00',
      temp_c: 28.1,
      temp_f: 82.6,
      is_day: 0,
      condition: {
        text: '所により曇り',
        icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
        code: 1003,
      },
      wind_mph: 10.1,
      wind_kph: 16.2,
      wind_degree: 225,
      wind_dir: 'SW',
      pressure_mb: 1008.0,
      pressure_in: 29.77,
      precip_mm: 0.18,
      precip_in: 0.01,
      snow_cm: 0.0,
      humidity: 74,
      cloud: 25,
      feelslike_c: 32.1,
      feelslike_f: 89.7,
      windchill_c: 28.7,
      windchill_f: 83.6,
      heatindex_c: 32.1,
      heatindex_f: 89.7,
      dewpoint_c: 22.5,
      dewpoint_f: 72.6,
      will_it_rain: 1,
      chance_of_rain: 100,
      will_it_snow: 0,
      chance_of_snow: 0,
      vis_km: 10.0,
      vis_miles: 6.0,
      gust_mph: 13.4,
      gust_kph: 21.5,
      uv: 0,
    },
    {
      time_epoch: 1726246800,
      time: '2024-09-14 02:00',
      temp_c: 28.6,
      temp_f: 83.4,
      is_day: 0,
      condition: {
        text: '所により曇り',
        icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
        code: 1003,
      },
      wind_mph: 8.5,
      wind_kph: 13.7,
      wind_degree: 231,
      wind_dir: 'SW',
      pressure_mb: 1008.0,
      pressure_in: 29.76,
      precip_mm: 0.0,
      precip_in: 0.0,
      snow_cm: 0.0,
      humidity: 71,
      cloud: 25,
      feelslike_c: 32.1,
      feelslike_f: 89.7,
      windchill_c: 28.6,
      windchill_f: 83.4,
      heatindex_c: 32.1,
      heatindex_f: 89.7,
      dewpoint_c: 22.7,
      dewpoint_f: 72.9,
      will_it_rain: 0,
      chance_of_rain: 0,
      will_it_snow: 0,
      chance_of_snow: 0,
      vis_km: 10.0,
      vis_miles: 6.0,
      gust_mph: 11.4,
      gust_kph: 18.4,
      uv: 0,
    },
  ],
};

export const mockForecastWeather: ForecastResponse = {
  location: {
    name: 'Tokyo',
    region: 'Tokyo',
    country: 'Japan',
    lat: 35.69,
    lon: 139.69,
    tz_id: 'Asia/Tokyo',
    localtime_epoch: 1726247716,
    localtime: '2024-09-14 02:15',
  },
  current: {
    last_updated_epoch: 1726246800,
    last_updated: '2024-09-14 02:00',
    temp_c: 28.1,
    temp_f: 82.6,
    is_day: 0,
    condition: {
      text: '所により曇り',
      icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
      code: 1003,
    },
    wind_mph: 8.5,
    wind_kph: 13.7,
    wind_degree: 231,
    wind_dir: 'SW',
    pressure_mb: 1008.0,
    pressure_in: 29.77,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 74,
    cloud: 25,
    feelslike_c: 31.2,
    feelslike_f: 88.1,
    windchill_c: 28.6,
    windchill_f: 83.4,
    heatindex_c: 32.1,
    heatindex_f: 89.7,
    dewpoint_c: 22.7,
    dewpoint_f: 72.9,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 11.4,
    gust_kph: 18.4,
  },
  forecast: {
    forecastday: [
      {
        date: '2024-09-14',
        date_epoch: 1726272000,
        day: {
          maxtemp_c: 32.5,
          maxtemp_f: 90.6,
          mintemp_c: 27.8,
          mintemp_f: 82.0,
          avgtemp_c: 29.8,
          avgtemp_f: 85.6,
          maxwind_mph: 20.6,
          maxwind_kph: 33.1,
          totalprecip_mm: 0.1,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 66,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: '所により曇り',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003,
          },
          uv: 8.0,
        },
        astro: {
          sunrise: '05:23 AM',
          sunset: '05:50 PM',
          moonrise: '03:36 PM',
          moonset: '12:14 AM',
          moon_phase: 'Waxing Gibbous',
          moon_illumination: 78,
          is_moon_up: 0,
          is_sun_up: 1,
        },
        hour: [],
      },
      {
        date: '2024-09-15',
        date_epoch: 1726358400,
        day: {
          maxtemp_c: 33.2,
          maxtemp_f: 91.8,
          mintemp_c: 28.0,
          mintemp_f: 82.4,
          avgtemp_c: 30.3,
          avgtemp_f: 86.6,
          maxwind_mph: 19.0,
          maxwind_kph: 30.6,
          totalprecip_mm: 1.15,
          totalprecip_in: 0.05,
          totalsnow_cm: 0.0,
          avgvis_km: 9.6,
          avgvis_miles: 5.0,
          avghumidity: 63,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 88,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: '近くで所により雨',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063,
          },
          uv: 8.0,
        },
        astro: {
          sunrise: '05:24 AM',
          sunset: '05:49 PM',
          moonrise: '04:16 PM',
          moonset: '01:26 AM',
          moon_phase: 'Waxing Gibbous',
          moon_illumination: 86,
          is_moon_up: 0,
          is_sun_up: 1,
        },
        hour: [],
      },
      {
        date: '2024-09-16',
        date_epoch: 1726444800,
        day: {
          maxtemp_c: 27.4,
          maxtemp_f: 81.3,
          mintemp_c: 25.1,
          mintemp_f: 77.2,
          avgtemp_c: 26.5,
          avgtemp_f: 79.7,
          maxwind_mph: 15.4,
          maxwind_kph: 24.8,
          totalprecip_mm: 18.36,
          totalprecip_in: 0.72,
          totalsnow_cm: 0.0,
          avgvis_km: 9.7,
          avgvis_miles: 6.0,
          avghumidity: 77,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 89,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: '穏やかな雨',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 5.0,
        },
        astro: {
          sunrise: '05:25 AM',
          sunset: '05:47 PM',
          moonrise: '04:52 PM',
          moonset: '02:40 AM',
          moon_phase: 'Waxing Gibbous',
          moon_illumination: 93,
          is_moon_up: 0,
          is_sun_up: 1,
        },
        hour: [],
      },
      {
        date: '2024-09-17',
        date_epoch: 1726531200,
        day: {
          maxtemp_c: 31.4,
          maxtemp_f: 88.5,
          mintemp_c: 25.1,
          mintemp_f: 77.1,
          avgtemp_c: 28.0,
          avgtemp_f: 82.4,
          maxwind_mph: 14.3,
          maxwind_kph: 23.0,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 68,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: '所により曇り',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003,
          },
          uv: 7.0,
        },
        astro: {
          sunrise: '05:26 AM',
          sunset: '05:46 PM',
          moonrise: '05:23 PM',
          moonset: '03:55 AM',
          moon_phase: 'Waxing Gibbous',
          moon_illumination: 98,
          is_moon_up: 0,
          is_sun_up: 1,
        },
        hour: [],
      },
      {
        date: '2024-09-18',
        date_epoch: 1726617600,
        day: {
          maxtemp_c: 32.2,
          maxtemp_f: 90.0,
          mintemp_c: 27.8,
          mintemp_f: 82.1,
          avgtemp_c: 29.5,
          avgtemp_f: 85.1,
          maxwind_mph: 20.1,
          maxwind_kph: 32.4,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 65,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: '晴れ',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000,
          },
          uv: 7.0,
        },
        astro: {
          sunrise: '05:26 AM',
          sunset: '05:44 PM',
          moonrise: '05:53 PM',
          moonset: '05:10 AM',
          moon_phase: 'Full Moon',
          moon_illumination: 100,
          is_moon_up: 0,
          is_sun_up: 1,
        },
        hour: [],
      },
      {
        date: '2024-09-19',
        date_epoch: 1726704000,
        day: {
          maxtemp_c: 31.6,
          maxtemp_f: 88.8,
          mintemp_c: 25.9,
          mintemp_f: 78.6,
          avgtemp_c: 29.2,
          avgtemp_f: 84.5,
          maxwind_mph: 23.5,
          maxwind_kph: 37.8,
          totalprecip_mm: 1.06,
          totalprecip_in: 0.04,
          totalsnow_cm: 0.0,
          avgvis_km: 9.9,
          avgvis_miles: 6.0,
          avghumidity: 66,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 72,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: '近くで所により雨',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063,
          },
          uv: 6.0,
        },
        astro: {
          sunrise: '05:27 AM',
          sunset: '05:43 PM',
          moonrise: '06:22 PM',
          moonset: '06:24 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: 99,
          is_moon_up: 0,
          is_sun_up: 1,
        },
        hour: [],
      },
      {
        date: '2024-09-20',
        date_epoch: 1726790400,
        day: {
          maxtemp_c: 25.9,
          maxtemp_f: 78.6,
          mintemp_c: 22.5,
          mintemp_f: 72.5,
          avgtemp_c: 24.3,
          avgtemp_f: 75.7,
          maxwind_mph: 25.7,
          maxwind_kph: 41.4,
          totalprecip_mm: 41.08,
          totalprecip_in: 1.62,
          totalsnow_cm: 0.0,
          avgvis_km: 7.1,
          avgvis_miles: 4.0,
          avghumidity: 90,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 85,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: '大雨',
            icon: '//cdn.weatherapi.com/weather/64x64/day/308.png',
            code: 1195,
          },
          uv: 5.0,
        },
        astro: {
          sunrise: '05:28 AM',
          sunset: '05:41 PM',
          moonrise: '06:53 PM',
          moonset: '07:39 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: 95,
          is_moon_up: 0,
          is_sun_up: 1,
        },
        hour: [],
      },
    ],
  },
};

export const mockHourData: HourData = {
  time_epoch: 1726239600,
  time: '2024-09-14 00:00',
  temp_c: 28.7,
  temp_f: 83.6,
  is_day: 0,
  condition: {
    text: '快晴',
    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
    code: 1000,
  },
  wind_mph: 13.4,
  wind_kph: 21.6,
  wind_degree: 210,
  wind_dir: 'SSW',
  pressure_mb: 1008.0,
  pressure_in: 29.77,
  precip_mm: 0.0,
  precip_in: 0.0,
  snow_cm: 0.0,
  humidity: 68,
  cloud: 13,
  feelslike_c: 31.9,
  feelslike_f: 89.5,
  windchill_c: 28.7,
  windchill_f: 83.6,
  heatindex_c: 31.9,
  heatindex_f: 89.5,
  dewpoint_c: 22.3,
  dewpoint_f: 72.1,
  will_it_rain: 0,
  chance_of_rain: 0,
  will_it_snow: 0,
  chance_of_snow: 0,
  vis_km: 10.0,
  vis_miles: 6.0,
  gust_mph: 17.8,
  gust_kph: 28.6,
  uv: 0,
};

export const mockSpecificDayWeather: SpecificDayResponse = {
  location: {
    name: 'Tokyo',
    region: 'Tokyo',
    country: 'Japan',
    lat: 35.69,
    lon: 139.69,
    tz_id: 'Asia/Tokyo',
    localtime_epoch: 1726249486,
    localtime: '2024-09-14 02:44',
  },
  forecast: {
    forecastday: [
      {
        date: '2024-09-15',
        date_epoch: 1726185600,
        day: {
          maxtemp_c: 32.7,
          maxtemp_f: 90.9,
          mintemp_c: 28.2,
          mintemp_f: 82.8,
          avgtemp_c: 30.0,
          avgtemp_f: 86.1,
          maxwind_mph: 20.1,
          maxwind_kph: 32.4,
          totalprecip_mm: 0.56,
          totalprecip_in: 0.02,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 65,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 89,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: '近くで所により雨',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063,
          },
          uv: 8.0,
        },
        astro: {
          sunrise: '05:23 AM',
          sunset: '05:52 PM',
          moonrise: '02:48 PM',
          moonset: 'No moonset',
          moon_phase: 'Waxing Gibbous',
          moon_illumination: 68,
          is_moon_up: 0,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1726153200,
            time: '2024-09-15 00:00',
            temp_c: 28.7,
            temp_f: 83.7,
            is_day: 0,
            condition: {
              text: '快晴',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 15.7,
            wind_kph: 25.2,
            wind_degree: 192,
            wind_dir: 'SSW',
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 73,
            cloud: 8,
            feelslike_c: 32.7,
            feelslike_f: 90.9,
            windchill_c: 28.7,
            windchill_f: 83.7,
            heatindex_c: 32.7,
            heatindex_f: 90.9,
            dewpoint_c: 23.4,
            dewpoint_f: 74.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 20.6,
            gust_kph: 33.1,
            uv: 0,
          },
          {
            time_epoch: 1726156800,
            time: '2024-09-15 01:00',
            temp_c: 28.5,
            temp_f: 83.3,
            is_day: 0,
            condition: {
              text: '快晴',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 14.5,
            wind_kph: 23.4,
            wind_degree: 198,
            wind_dir: 'SSW',
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 73,
            cloud: 8,
            feelslike_c: 32.4,
            feelslike_f: 90.2,
            windchill_c: 28.5,
            windchill_f: 83.3,
            heatindex_c: 32.4,
            heatindex_f: 90.2,
            dewpoint_c: 23.3,
            dewpoint_f: 73.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.2,
            gust_kph: 30.9,
            uv: 0,
          },
          {
            time_epoch: 1726160400,
            time: '2024-09-15 02:00',
            temp_c: 28.4,
            temp_f: 83.0,
            is_day: 0,
            condition: {
              text: '快晴',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 205,
            wind_dir: 'SSW',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 73,
            cloud: 8,
            feelslike_c: 32.0,
            feelslike_f: 89.7,
            windchill_c: 28.4,
            windchill_f: 83.0,
            heatindex_c: 32.0,
            heatindex_f: 89.7,
            dewpoint_c: 23.1,
            dewpoint_f: 73.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.0,
            gust_kph: 25.7,
            uv: 0,
          },
          {
            time_epoch: 1726164000,
            time: '2024-09-15 03:00',
            temp_c: 28.4,
            temp_f: 83.1,
            is_day: 0,
            condition: {
              text: '快晴',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 212,
            wind_dir: 'SSW',
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 74,
            cloud: 19,
            feelslike_c: 32.1,
            feelslike_f: 89.8,
            windchill_c: 28.4,
            windchill_f: 83.1,
            heatindex_c: 32.1,
            heatindex_f: 89.8,
            dewpoint_c: 23.2,
            dewpoint_f: 73.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.1,
            gust_kph: 21.1,
            uv: 0,
          },
          {
            time_epoch: 1726167600,
            time: '2024-09-15 04:00',
            temp_c: 28.3,
            temp_f: 82.9,
            is_day: 0,
            condition: {
              text: '快晴',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 220,
            wind_dir: 'SW',
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 74,
            cloud: 19,
            feelslike_c: 32.0,
            feelslike_f: 89.6,
            windchill_c: 28.3,
            windchill_f: 82.9,
            heatindex_c: 32.0,
            heatindex_f: 89.6,
            dewpoint_c: 23.2,
            dewpoint_f: 73.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.5,
            gust_kph: 16.9,
            uv: 0,
          },
          {
            time_epoch: 1726171200,
            time: '2024-09-15 05:00',
            temp_c: 28.2,
            temp_f: 82.8,
            is_day: 0,
            condition: {
              text: '快晴',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 220,
            wind_dir: 'SW',
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 74,
            cloud: 22,
            feelslike_c: 32.0,
            feelslike_f: 89.5,
            windchill_c: 28.2,
            windchill_f: 82.8,
            heatindex_c: 32.0,
            heatindex_f: 89.5,
            dewpoint_c: 23.3,
            dewpoint_f: 73.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.0,
            gust_kph: 14.5,
            uv: 0,
          },
          {
            time_epoch: 1726174800,
            time: '2024-09-15 06:00',
            temp_c: 28.2,
            temp_f: 82.8,
            is_day: 1,
            condition: {
              text: '所により曇り',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 219,
            wind_dir: 'SW',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 73,
            cloud: 25,
            feelslike_c: 31.8,
            feelslike_f: 89.3,
            windchill_c: 28.2,
            windchill_f: 82.8,
            heatindex_c: 31.8,
            heatindex_f: 89.3,
            dewpoint_c: 23.0,
            dewpoint_f: 73.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.0,
            gust_kph: 14.5,
            uv: 7.0,
          },
          {
            time_epoch: 1726178400,
            time: '2024-09-15 07:00',
            temp_c: 28.7,
            temp_f: 83.6,
            is_day: 1,
            condition: {
              text: '晴れ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 221,
            wind_dir: 'SW',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 71,
            cloud: 25,
            feelslike_c: 32.3,
            feelslike_f: 90.2,
            windchill_c: 28.7,
            windchill_f: 83.6,
            heatindex_c: 32.3,
            heatindex_f: 90.2,
            dewpoint_c: 22.9,
            dewpoint_f: 73.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.5,
            uv: 7.0,
          },
          {
            time_epoch: 1726182000,
            time: '2024-09-15 08:00',
            temp_c: 29.4,
            temp_f: 84.8,
            is_day: 1,
            condition: {
              text: '所により曇り',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 204,
            wind_dir: 'SSW',
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 68,
            cloud: 48,
            feelslike_c: 33.2,
            feelslike_f: 91.8,
            windchill_c: 29.4,
            windchill_f: 84.8,
            heatindex_c: 33.2,
            heatindex_f: 91.8,
            dewpoint_c: 22.8,
            dewpoint_f: 73.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.2,
            gust_kph: 13.2,
            uv: 7.0,
          },
          {
            time_epoch: 1726185600,
            time: '2024-09-15 09:00',
            temp_c: 30.3,
            temp_f: 86.5,
            is_day: 1,
            condition: {
              text: '所により曇り',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 189,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 64,
            cloud: 51,
            feelslike_c: 34.4,
            feelslike_f: 93.8,
            windchill_c: 30.3,
            windchill_f: 86.5,
            heatindex_c: 34.4,
            heatindex_f: 93.8,
            dewpoint_c: 22.6,
            dewpoint_f: 72.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.0,
            gust_kph: 16.2,
            uv: 8.0,
          },
          {
            time_epoch: 1726189200,
            time: '2024-09-15 10:00',
            temp_c: 31.2,
            temp_f: 88.2,
            is_day: 1,
            condition: {
              text: '晴れ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 184,
            wind_dir: 'S',
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 59,
            cloud: 21,
            feelslike_c: 35.3,
            feelslike_f: 95.5,
            windchill_c: 31.2,
            windchill_f: 88.2,
            heatindex_c: 35.3,
            heatindex_f: 95.5,
            dewpoint_c: 22.3,
            dewpoint_f: 72.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.3,
            gust_kph: 19.9,
            uv: 8.0,
          },
          {
            time_epoch: 1726192800,
            time: '2024-09-15 11:00',
            temp_c: 31.9,
            temp_f: 89.5,
            is_day: 1,
            condition: {
              text: '晴れ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 182,
            wind_dir: 'S',
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 56,
            cloud: 9,
            feelslike_c: 36.2,
            feelslike_f: 97.1,
            windchill_c: 31.9,
            windchill_f: 89.5,
            heatindex_c: 36.2,
            heatindex_f: 97.1,
            dewpoint_c: 22.2,
            dewpoint_f: 71.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.7,
            gust_kph: 23.6,
            uv: 8.0,
          },
          {
            time_epoch: 1726196400,
            time: '2024-09-15 12:00',
            temp_c: 32.4,
            temp_f: 90.4,
            is_day: 1,
            condition: {
              text: '晴れ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 15.4,
            wind_kph: 24.8,
            wind_degree: 179,
            wind_dir: 'S',
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 56,
            cloud: 6,
            feelslike_c: 37.2,
            feelslike_f: 98.9,
            windchill_c: 32.4,
            windchill_f: 90.4,
            heatindex_c: 37.2,
            heatindex_f: 98.9,
            dewpoint_c: 22.5,
            dewpoint_f: 72.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.8,
            gust_kph: 28.6,
            uv: 8.0,
          },
          {
            time_epoch: 1726200000,
            time: '2024-09-15 13:00',
            temp_c: 32.7,
            temp_f: 90.9,
            is_day: 1,
            condition: {
              text: '晴れ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 16.8,
            wind_kph: 27.0,
            wind_degree: 181,
            wind_dir: 'S',
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 55,
            cloud: 4,
            feelslike_c: 37.6,
            feelslike_f: 99.7,
            windchill_c: 32.7,
            windchill_f: 90.9,
            heatindex_c: 37.6,
            heatindex_f: 99.7,
            dewpoint_c: 22.6,
            dewpoint_f: 72.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.3,
            gust_kph: 31.1,
            uv: 8.0,
          },
          {
            time_epoch: 1726203600,
            time: '2024-09-15 14:00',
            temp_c: 32.5,
            temp_f: 90.5,
            is_day: 1,
            condition: {
              text: '晴れ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 18.8,
            wind_kph: 30.2,
            wind_degree: 181,
            wind_dir: 'S',
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 56,
            cloud: 4,
            feelslike_c: 37.2,
            feelslike_f: 99.0,
            windchill_c: 32.5,
            windchill_f: 90.4,
            heatindex_c: 37.2,
            heatindex_f: 99.0,
            dewpoint_c: 22.5,
            dewpoint_f: 72.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.6,
            gust_kph: 34.8,
            uv: 8.0,
          },
          {
            time_epoch: 1726207200,
            time: '2024-09-15 15:00',
            temp_c: 32.0,
            temp_f: 89.7,
            is_day: 1,
            condition: {
              text: '晴れ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 20.1,
            wind_kph: 32.4,
            wind_degree: 181,
            wind_dir: 'S',
            pressure_mb: 1007.0,
            pressure_in: 29.74,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 57,
            cloud: 3,
            feelslike_c: 36.6,
            feelslike_f: 97.9,
            windchill_c: 32.0,
            windchill_f: 89.7,
            heatindex_c: 36.6,
            heatindex_f: 97.9,
            dewpoint_c: 22.5,
            dewpoint_f: 72.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.2,
            gust_kph: 37.3,
            uv: 8.0,
          },
          {
            time_epoch: 1726210800,
            time: '2024-09-15 16:00',
            temp_c: 31.7,
            temp_f: 89.0,
            is_day: 1,
            condition: {
              text: '晴れ',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 19.9,
            wind_kph: 32.0,
            wind_degree: 182,
            wind_dir: 'S',
            pressure_mb: 1007.0,
            pressure_in: 29.75,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 59,
            cloud: 12,
            feelslike_c: 36.1,
            feelslike_f: 97.0,
            windchill_c: 31.7,
            windchill_f: 89.0,
            heatindex_c: 36.1,
            heatindex_f: 97.0,
            dewpoint_c: 22.5,
            dewpoint_f: 72.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 22.9,
            gust_kph: 36.9,
            uv: 8.0,
          },
          {
            time_epoch: 1726214400,
            time: '2024-09-15 17:00',
            temp_c: 31.3,
            temp_f: 88.3,
            is_day: 1,
            condition: {
              text: '近くで所により雨',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 19.2,
            wind_kph: 31.0,
            wind_degree: 185,
            wind_dir: 'S',
            pressure_mb: 1007.0,
            pressure_in: 29.75,
            precip_mm: 0.01,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 60,
            cloud: 76,
            feelslike_c: 35.6,
            feelslike_f: 96.1,
            windchill_c: 31.3,
            windchill_f: 88.3,
            heatindex_c: 35.6,
            heatindex_f: 96.1,
            dewpoint_c: 22.5,
            dewpoint_f: 72.5,
            will_it_rain: 1,
            chance_of_rain: 78,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.2,
            gust_kph: 37.4,
            uv: 7.0,
          },
          {
            time_epoch: 1726218000,
            time: '2024-09-15 18:00',
            temp_c: 30.7,
            temp_f: 87.2,
            is_day: 0,
            condition: {
              text: '近くで所により雨',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 18.3,
            wind_kph: 29.5,
            wind_degree: 187,
            wind_dir: 'S',
            pressure_mb: 1008.0,
            pressure_in: 29.75,
            precip_mm: 0.25,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 62,
            cloud: 72,
            feelslike_c: 34.8,
            feelslike_f: 94.6,
            windchill_c: 30.7,
            windchill_f: 87.2,
            heatindex_c: 34.8,
            heatindex_f: 94.6,
            dewpoint_c: 22.5,
            dewpoint_f: 72.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 23.5,
            gust_kph: 37.8,
            uv: 0,
          },
          {
            time_epoch: 1726221600,
            time: '2024-09-15 19:00',
            temp_c: 30.4,
            temp_f: 86.8,
            is_day: 0,
            condition: {
              text: '近くで所により雨',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 17.9,
            wind_kph: 28.8,
            wind_degree: 195,
            wind_dir: 'SSW',
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.09,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 61,
            cloud: 89,
            feelslike_c: 34.2,
            feelslike_f: 93.5,
            windchill_c: 30.5,
            windchill_f: 86.8,
            heatindex_c: 34.2,
            heatindex_f: 93.5,
            dewpoint_c: 22.1,
            dewpoint_f: 71.8,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.3,
            gust_kph: 37.5,
            uv: 0,
          },
          {
            time_epoch: 1726225200,
            time: '2024-09-15 20:00',
            temp_c: 29.7,
            temp_f: 85.5,
            is_day: 0,
            condition: {
              text: '近くで所により雨',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 17.2,
            wind_kph: 27.7,
            wind_degree: 196,
            wind_dir: 'SSW',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.09,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 63,
            cloud: 70,
            feelslike_c: 33.2,
            feelslike_f: 91.7,
            windchill_c: 29.7,
            windchill_f: 85.5,
            heatindex_c: 33.2,
            heatindex_f: 91.7,
            dewpoint_c: 22.0,
            dewpoint_f: 71.6,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 22.4,
            gust_kph: 36.0,
            uv: 0,
          },
          {
            time_epoch: 1726228800,
            time: '2024-09-15 21:00',
            temp_c: 29.4,
            temp_f: 84.9,
            is_day: 0,
            condition: {
              text: '近くで所により雨',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 16.1,
            wind_kph: 25.9,
            wind_degree: 199,
            wind_dir: 'SSW',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.12,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 64,
            cloud: 88,
            feelslike_c: 32.7,
            feelslike_f: 90.9,
            windchill_c: 29.4,
            windchill_f: 84.9,
            heatindex_c: 32.7,
            heatindex_f: 90.9,
            dewpoint_c: 22.0,
            dewpoint_f: 71.6,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.2,
            gust_kph: 34.1,
            uv: 0,
          },
          {
            time_epoch: 1726232400,
            time: '2024-09-15 22:00',
            temp_c: 29.1,
            temp_f: 84.4,
            is_day: 0,
            condition: {
              text: '快晴',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 15.4,
            wind_kph: 24.8,
            wind_degree: 203,
            wind_dir: 'SSW',
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 65,
            cloud: 21,
            feelslike_c: 32.3,
            feelslike_f: 90.2,
            windchill_c: 29.1,
            windchill_f: 84.4,
            heatindex_c: 32.3,
            heatindex_f: 90.2,
            dewpoint_c: 22.0,
            dewpoint_f: 71.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 20.2,
            gust_kph: 32.5,
            uv: 0,
          },
          {
            time_epoch: 1726236000,
            time: '2024-09-15 23:00',
            temp_c: 28.9,
            temp_f: 84.1,
            is_day: 0,
            condition: {
              text: '快晴',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 205,
            wind_dir: 'SSW',
            pressure_mb: 1008.0,
            pressure_in: 29.78,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 67,
            cloud: 17,
            feelslike_c: 32.1,
            feelslike_f: 89.8,
            windchill_c: 28.9,
            windchill_f: 84.1,
            heatindex_c: 32.1,
            heatindex_f: 89.8,
            dewpoint_c: 22.1,
            dewpoint_f: 71.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.3,
            gust_kph: 31.1,
            uv: 0,
          },
        ],
      },
    ],
  },
};
